# stylish-haskell configuration file
# ==================================

# The stylish-haskell tool is mainly configured by specifying steps. These steps
# are a list, so they have an order, and one specific step may appear more than
# once (if needed). Each file is processed by these steps in the given order.
steps:
  # - unicode_syntax:
  #     add_language_pragma: true

  - module_header:
      indent: 2
      sort: true
      separate_lists: true
      break_where: exports
      open_bracket: next_line

  - simple_align:
      cases: always
      top_level_patterns: always
      records: always
      multi_way_if: always

  - imports:
      align: global
      list_align: after_alias
      pad_module_names: true
      long_list_align: inline
      empty_list_align: inherit
      list_padding: 2
      separate_lists: true
      space_surround: true
      post_qualify: true


  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: true
      language_prefix: LANGUAGE

  - trailing_whitespace: {}

columns: 120
newline: native

language_extensions:
  - DataKinds
  - GADTs
  - LambdaCase
  - TemplateHaskell
  - TypeFamilies
  - TypeInType
  - TypeOperators
  - UndecidableInstances

cabal: true

records:
  equals: "indent 2"
  first_field: "indent 2"
  field_comment: 2
  deriving: 2
  via: "indent 2"
  sort_deriving: true
  break_enums: false
  break_single_constructors: true
  curried_context: false
